spring:
  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: users

      kafka:
        bindings:
          process-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.DelegatingDeserializer

        binder:
          brokers:
            - localhost:9091
            - localhost:9092
